#!/usr/bin/env python3
"""Seeded synthetic fixture generator (sellers/products/orders).

Deterministic: same seed -> same output. Uses faker when installed for
locale-aware pools; otherwise built-in synthetic pools. Output conforms
to seed/validators/fixtures.schema.json.
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("pyyaml is required: pip install -e .")

ROOT = Path(__file__).resolve().parents[2]
CATEGORIES = ROOT / "seed/taxonomy/categories.yml"
VAT_RATES = ROOT / "seed/tax/vat-rates.yml"

COUNTRIES = ["LT", "LV", "EE"]
LEGAL_FORMS = {"LT": ["sole-trader", "uab"], "LV": ["sole-trader", "sia"], "EE": ["sole-trader", "ou"]}
TITLES = [
    "Synthetic brass candelabrum", "Synthetic linen alb", "Synthetic icon panel",
    "Synthetic hymnal", "Synthetic ceremonial set", "Synthetic granite marker",
    "Synthetic ceremony service", "Synthetic prayer book",
]
STATUSES_ORDER = ["paid", "shipped", "delivered", "refunded", "cancelled"]


def load_yaml(path: Path) -> dict:
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def generate(seed: int, n_sellers: int = 5, n_products: int = 8, n_orders: int = 10) -> dict:
    rng = random.Random(seed)
    cats = load_yaml(CATEGORIES)["categories"]
    rates = load_yaml(VAT_RATES)["rates"]
    cat_vat = {c["code"]: c["vat_class"] for c in cats}

    sellers = []
    for i in range(1, n_sellers + 1):
        country = rng.choice(COUNTRIES)
        sellers.append({
            "seller_key": f"SYN-SLR-{i:04d}",
            "legal_form": rng.choice(LEGAL_FORMS[country]),
            "country": country,
            "joined_at": f"2026-{rng.randint(1, 6):02d}-{rng.randint(1, 28):02d}",
            "active": rng.random() > 0.15,
        })

    products = []
    for i in range(1, n_products + 1):
        cat = rng.choice(cats)["code"]
        products.append({
            "product_key": f"SYN-PRD-{i:04d}",
            "seller_key": rng.choice(sellers)["seller_key"],
            "category_code": cat,
            "title": rng.choice(TITLES),
            "price_cents": rng.randint(1500, 60000),
            "currency": "EUR",
            "status": rng.choice(["active", "active", "active", "inactive"]),
        })

    orders = []
    for i in range(1, n_orders + 1):
        product = rng.choice(products)
        seller = next(s for s in sellers if s["seller_key"] == product["seller_key"])
        country = rng.choice(COUNTRIES)
        vat = rates[country][cat_vat[product["category_code"]]]
        orders.append({
            "order_key": f"SYN-ORD-{i:04d}",
            "buyer_key": f"SYN-BUY-{rng.randint(1, 20):04d}",
            "seller_key": seller["seller_key"],
            "product_key": product["product_key"],
            "amount_cents": product["price_cents"],
            "currency": "EUR",
            "country": country,
            "vat_rate_pct": float(vat),
            "status": rng.choice(STATUSES_ORDER),
            "ordered_at": f"2026-08-{rng.randint(1, 14):02d}T{rng.randint(8, 19):02d}:00:00Z",
        })

    return {"sellers": sellers, "products": products, "orders": orders}


def write(data: dict, out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    for name, records in data.items():
        with open(out / f"{name}.yml", "w", encoding="utf-8") as fh:
            fh.write("# Synthetic fixture — generated by synthetic/generators.\n")
            yaml.safe_dump({"schema_version": 1, "records": records}, fh,
                           sort_keys=False, allow_unicode=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--out", type=Path, default=ROOT / "seed/fixtures")
    args = parser.parse_args()
    write(generate(args.seed), args.out)
    print(f"wrote synthetic fixtures (seed={args.seed}) to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
